app/models/chat.rb
app/models/doc.rb
app/models/doc_chat.rb
app/models/message.rb
app/models/response.rb
db/migrate/20230805082708_create_docs.rb
db/migrate/20230805082731_create_chats.rb
db/migrate/20230805083011_create_doc_chats.rb
db/migrate/20230805083025_create_messages.rb
db/migrate/20230805083035_create_responses.rb
db/migrate/20230805083129_add_fields_to_users.rb
db/schema.rb
test/models/chat_test.rb
test/models/doc_chat_test.rb
test/models/doc_test.rb
test/models/message_test.rb
test/models/response_test.rb

please check schema and models

created models

---

db/migrate/20230805085333_add_fields_to_users.rb
db/schema.rb

updated models

---

app/controllers/chats_controller.rb
app/controllers/docs_controller.rb
test/controllers/chats_controller_test.rb
test/controllers/docs_controller_test.rb

created controllers

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/policies/application_policy.rb

pundit setup  updated

---

app/controllers/docs_controller.rb
app/policies/doc_policy.rb
app/views/docs/index.html.erb
app/views/docs/show.html.erb
test/policies/doc_policy_test.rb

created the create action and index action for doc

created the create action for doc

---

.gitignore
Gemfile
Gemfile.lock
app/services/openai_service.rb
config/initializers/openai.rb

Please check. Set up Open AI as a service

set up open ai as a service

---

app/views/shared/_navbar.html.erb

fixed navbar so heroku can run

---

app/assets/stylesheets/pages/_index.scss
app/views/docs/index.html.erb

updated some css to make it look better

modified some css

---

app/views/shared/_navbar.html.erb

I have resized the avatar, but the dropdown menu is still not working.

resized the avatar to align with the navbar

---

app/controllers/chats_controller.rb
app/views/chats/new.html.erb

created the chat#new and chat#create actions in chat controller, and created the new.html.erb for chat view. Now a user can create a new chat and send messages in the chatroom he or she created

created the chat new function and chat new view to create a new chat

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/javascript/application.js
config/initializers/assets.rb
package.json
yarn.lock

did fix according to instructor guidance

fixed drop down

---

app/controllers/chats_controller.rb
app/controllers/messages_controller.rb
app/controllers/responses_controller.rb
app/javascript/controllers/chat_subscription_controller.js
app/policies/response_policy.rb
app/views/chats/show.html.erb
app/views/messages/_message.html.erb
app/views/messages/_response.html.erb
config/routes.rb
db/migrate/20230812054807_add_responses_to_messages.rb
db/schema.rb
test/controllers/responses_controller_test.rb
test/policies/response_policy_test.rb

please check (please dont delete this one; I want to study this one)

added open ai and response handling logic

---

app/controllers/responses_controller.rb

updated responses

---

app/controllers/docs_controller.rb
app/controllers/messages_controller.rb
app/views/shared/_navbar.html.erb

I redesigned the navbar and added a search function within the navbar and you can search doc now.

added the search bar within the navbar and we can search the docs now

---

app/assets/stylesheets/chats/_show.scss
app/assets/stylesheets/pages/_index.scss
app/views/docs/index.html.erb
app/views/shared/_chats.html.erb

modified css for the chat session and add scrow bar

---

app/controllers/chats_controller.rb
app/controllers/messages_controller.rb
app/models/chat.rb
app/views/chats/new.html.erb
app/views/docs/index.html.erb

It is super cool now. Once we selected any doc and start conversation, the openAi can read the data and we can ask any questions about the data and OpenAi can response to it.

our openAI can interact with the doc now

---

app/views/docs/index.html.erb

fixed html

---

app/controllers/messages_controller.rb

I added if statement in the messages controller to make it works out for our general chatroom!

fixed the general chat problems

---

app/assets/stylesheets/components/_doc_upload_form.scss
app/assets/stylesheets/components/_index.scss
app/javascript/controllers/dropzone_controller.js
app/javascript/controllers/index.js
app/views/docs/index.html.erb
app/views/shared/_doc-upload.html.erb
package.json
yarn.lock

Added styling to the doc upload section

Doc upload view

---

app/assets/stylesheets/chats/_show.scss
app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/pages/_index.scss
app/views/chats/index.html.erb
app/views/chats/new.html.erb
app/views/docs/index.html.erb
app/views/shared/_sidebar.html.erb

updated sidebar to show on every screen and also adjust the chat height to show in one screen

Sidebar update

---

app/assets/stylesheets/pages/_index.scss
app/views/layouts/application.html.erb

added responsive code for the view

added responsive code

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/chats/_show.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_new_chat_container.scss
app/assets/stylesheets/pages/_index.scss
app/views/chats/new.html.erb

add the containner

---

app/assets/stylesheets/chats/_show.scss
app/controllers/messages_controller.rb
app/views/messages/_response.html.erb
app/views/shared/_chats.html.erb
db/migrate/20230819080151_add_from_ai_to_messages.rb
db/schema.rb

please check. I created a new migration so you will need to run rails db:migrate

fixed color change in chat, still buddy

---

app/javascript/controllers/chat_subscription_controller.js
app/views/messages/_message.html.erb
app/views/messages/_response.html.erb

got color change working for user and ai in chat

---

app/controllers/chats_controller.rb
app/views/chats/new.html.erb

OpenAI can talk to multiple docs right now.

OpenAI can talk to multiple docs in the same time now

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/chats/_new.scss
app/views/chats/new.html.erb

1. reorganized the design for the chat#new page
2. added instructions for the users 
3. show the selected files for user's reference
4. optimized the design for the checkbox list

redesinged the chat new page and added instruction for users

---

app/assets/stylesheets/pages/_index.scss
app/controllers/docs_controller.rb
app/policies/doc_policy.rb
app/views/docs/index.html.erb
config/routes.rb
package.json
yarn.lock

functioning delete button

---

app/assets/stylesheets/chats/_index.scss
app/assets/stylesheets/chats/_new.scss
app/views/chats/new.html.erb

I retrieved to the old version of the chat new version, which functions well.

changed the chat new version to the old version

---

app/assets/stylesheets/pages/_index.scss
app/views/docs/index.html.erb

small modify for the button

---

app/assets/stylesheets/chats/_show.scss
app/assets/stylesheets/pages/_index.scss
app/views/shared/_active-chat-session.html.erb

updated chat ui

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/pages/_index.scss
app/views/docs/index.html.erb
app/views/shared/_sidebar.html.erb

Elements don't overlap anymore

Overlapping html

---

app/views/chats/new.html.erb

fixed the chat new issue

---

app/assets/stylesheets/chats/_show.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/pages/_index.scss
app/views/docs/index.html.erb

updated the css for the sidebar and the doc index page

---

app/assets/stylesheets/chats/_show.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/docs_controller.rb
app/views/docs/index.html.erb
app/views/shared/_active-chat-session.html.erb

This is the code where I added the chat info icon + made some simple changes to the card and layout spacing

Docstash UI

---

app/assets/stylesheets/chats/_new.scss
app/controllers/chats_controller.rb
app/javascript/controllers/modal_controller.js
app/models/chat.rb
app/views/chats/new.html.erb
app/views/docs/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb

new chat modal is working now.

New chat modal

---

app/assets/stylesheets/chats/_new.scss
app/javascript/controllers/modal_controller.js
app/views/chats/new.html.erb

you can scroll the modal for the new chat now.

the new chat modal can be scrolled now

---

app/assets/stylesheets/pages/_index.scss
app/views/docs/index.html.erb

1. Deleted the description in the doc card
2. renamed the buttons within the card.

deleted the description in the doc card and renamed the buttons

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_send_button.scss
app/views/shared/_active-chat-session.html.erb

Changed the color of send button to make it better align our design

aligned the color of send button to the overall ui color

---

app/views/messages/_response.html.erb

fixed date and time not displaying for ai

fixed date and time not displaying for ai

---

app/assets/stylesheets/chats/_show.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_report_button.scss
app/javascript/controllers/chat_subscription_controller.js
app/views/shared/_active-chat-session.html.erb

1. added a generate report button which allows user to downloaded all the ai messages.
2. added some style to the report button to align the overall design

Report button

---

app/assets/stylesheets/pages/_index.scss

added 100vw to the content container to fix the a ui bug
